### ISSUE TITLE
Sort in columns instead of rows

### ISSUE THREAD

**Issue by AlvaroR156** [frankko/Artboard-Tools#14]
Could be possible to add the option to sort in columns instead of rows? 
So, "starting a new row when the pattern is broken" to be "starting a new row or column when the pattern is broken". It would look like that:
```
A A A
A A A 
  A A
  A
  A
```
It can be assign to a new shortcut: ( ctrl+opt+2 )
Thanks for the plugin.

**Comment by frankko** [comment]
Interesting idea. I’ll look into it.

**Comment by daniel0104** [comment]
Thanks for the plugin. This option would be super useful for me too, so that I don't have to modify it after each update.. :)
