### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by mischugo** [frankko/Artboard-Tools#4]
Hello,
is there any easy way to change shortcuts? The shortcut cmd+ctrl+1 is in conflict with the plugin "sketch.measure"

Best regards,

**Comment by frankko** [comment]
If you control-click the .sketchplugin file and select “Show Package Contents”, then make your way through the folders Contents then Sketch, you’ll see a file called “manifest.json”. Open that in a text editor. You can change line seven,

```
"shortcut" : "control command 1”,
```

to whatever you like.

**Comment by mischugo** [comment]
Hello,
Perfect. Thanks a lot!
